Fix the code sample
`Traceback (most recent call last):
  File "OneDriveTest.py", line 9, in <module>
    client_id='XXXXXXXXXXXXXXXX)
TypeError: get_default_client() missing 1 required positional argument: 'scopes'`

For this sample, I think `onedrivesdk.get_default_client()` need the argument `scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']`